[package]
name = "tui_tetris"
version = "0.1.0"
authors = ["Aurorans Solis <primalucegd@gmail.com>"]

[dependencies]
termion = "1.5.3"
config = "0.9.3"
toml = "0.5.0"
serde = { version = "1.0.90", features = ["derive"] }